---
title: 중간고사 (2025.10.28)
author: 최규빈
date: 10/28/2025
reference-location: margin
citation-location: margin
cap-location: margin
comments: false
draft: false
format: html
---

{{<video https://youtu.be/playlist?list=PLQqh36zP38-w3QpsLAD3t25vIS-gRYWI-&si=VIxd4NRmuSxBVQsZ>}}


## 1. 바늘이 하나 있는 시계 -- 20점

우리는 단순한 시계 하나를 생각해볼 수 있다. 이 시계에는 바늘이 하나 있고, 이 바늘을 무작위로 돌렸을 때, 바늘이 시계에서 어떤 위치에 멈추게 될 확률을 계산하는 상황을 상상해보자.

여기서 시계의 위치를 **각도**로 나타낸다. 시계의 각도는 $0$에서 $2\pi$ 사이로 표현된다. 즉, 시계바늘이 12시를 가리킬 때는 각도가 $0$이고, 시계바늘이 시계 방향으로 6시를 가리킬 때는 각도가 $\pi$이다. 이 문제에서 전체 각도 공간을 **sample space** $\Omega$로 정의한다. $\Omega = [0, 2\pi)$는 시계의 모든 각도를 나타내는 구간이다. 


시계바늘이 $0$부터 $2\pi$ 사이의 각도를 랜덤하게 가리킨다고 가정할 때, 우리는 특정 각도 범위 $\Omega^*$에 바늘이 있을 확률을 아래와 같이 계산할 수 있다. 

$$
P(\Omega^*) = \frac{m(\Omega^*)}{2\pi}
$$

여기에서 $m$는 길이를 재는 함수이다. 길이를 재는 함수 $m$에 대하여 아래와 같은 약속을 하자. 

- 약속1: 구간 $(a,b)$의 길이는 $b-a$이다. 즉 $m((a,b))=b-a$ 이다. 
- 약속2: 한 점의 길이는 0이다. 
- 약속3: 점을 무한히 합치면 선이 되는것 처럼, 점의 길이를 무한히 합치면 0이 아니라 0보다 큰 어떠한 수가 된다. 
- 약속4: 구간 $(a,b)$사이의 모든 무리수의 길이는 $b-a$이다. 

이와 같은 방식으로 길이를 잰다면 확률을 정의함에 있어서 모순이 일어나지 않는가? 모순이 일어나지 않으면 모순이 없다고 답을 쓰고 모순이 일어난다면 모순이 일어나는 이유를 설명하라. 

`(풀이)`

구간 $(a,b)$사이의 모든 무리수의 길이는 $b-a$라는 것은 구간 $(a,b)$사이의 모든 유리수의 길이가 $0$이라는 의미가 된다. 그런데 이것은 약속3에 모순이 된다. 


## 2. 수학과의 표현 -- 20점

아래가 의미하는 바를 한국어로 풀어 작성하라. (의역도 정답으로 인정)

`(1)` $\forall n,m \in \mathbb{N}: n+m \in \mathbb{N}$. 

`(풀이)`

두 자연수를 더한 결과는 항상 자연수이다. 


`(2)` $\forall a \in \mathbb{N}: \exists b \in \mathbb{Z}$ such that $a+b=0$. 


`(풀이)`

모든 자연수 $a$는 덧셈에 대한 역원 $b$를 정수범위에서 가진다. 


---

아래를 만족하는 함수 $f:X \to Y$가 어떠한 함수인지 판단하라. 

> 전사, 단사, 전단사중 하나를 답으로 쓰면 됩니다. 

`(3)` $\forall x, x' \in X, f(x)=f(x') \Longrightarrow x=x'$ 

`(풀이)`

단사함수


`(4)` $\forall y \in Y, \exists x \in X$ such that $y=f(x)$

`(풀이)`

전사함수 


## 3. 유리수의 카디널리티 -- 20점

자연수와 $[0,1]\cap \mathbb{Q}$^[구간 $[0,1]$사이의 유리수]의 카디널리티가 동일함을 보여라. (단, 이 문제에서 $|\mathbb{Q}|=\aleph_0$ 임은 모른다고 가정)

`(풀이)`

$Q=[0,1]\cap \mathbb{Q}$ 라고 정의하자. $f(n)=\frac{1}{n}$이라면 $f$는 $\mathbb{N} \to Q$인 단사함수이다. 이제 아래와 같은 무한집합을 생각하자. 

$$\{a_1,a_2,a_3,a_4,a_5,\dots,\}=\{\frac{1}{2},\frac{2}{2},\frac{1}{3},\frac{2}{3},\frac{3}{3},\dots\}$$

함수 $a(n)=a_n$은 $\mathbb{N}\to Q$인 전사함수가 된다. 따라서 $\mathbb{N}$와 $Q$의 카디널리티는 동일하다. 


## 4. 실수의 카디널리티 -- 20점 

자연수집합 $\mathbb{N}$에서 $[0,1]$로의 전사함수가 존재하지 않음을 보여라. 

`(풀이)`

생략

## 5. 카디널리티와 전단사함수 -- 20점

`(1)` 자연수집합 $\mathbb{N}$과 3의배수의 집합 $\{3,6,9,\dots\}$의 카디널리티를 비교하고, 두 집합의 카디널리티가 서로 다른지 또는 같은지를 판단한 뒤, 그 이유를 설명하라. 

`(풀이)` 

$f(n)=3n$은 자연수집합에서 3의배수의 집합으로가는 전단사함수이므로 두 집합의 카디널리티는 동일하다. 

`(2)` 구간 $[0,1]$과 $[0,2]$의 카디널리티를 비교하고, 두 집합의 카디널리티가 서로 다른지 또는 같은지를 판단한 뒤, 그 이유를 설명하라. 

`(풀이)` 

$f(x)=2x$은 $[0,1] \to [0,2]$인 전단사함수이므로 두 집합의 카디널리티는 동일하다. 

`(3)` 함수 $f:\mathbb{R}\to\mathbb{R}$가 $f(x)=x^2$로 정의되어 있을 때, 이 함수가 전사함수인지 아닌지 단사함수인지 아닌지 판단하고 그 근거를 설명하라.

`(풀이)` 

$f(-1)=f(1)=1$ 이므로 단사가 아니고, $f(x)=-1$에 대응하는 $x$가 $\mathbb{R}$에 존재하지 않으므로 전사가 아니다. 


`(4)` 함수 $f:\mathbb{R}^+\to \mathbb{R}^+$가 $f(x)=\sqrt{x}$로 정의되어 있을 때, 이 함수가 전사함수인지 아닌지 단사함수인지 아닌지 판단하고 그 근거를 설명하라. (단, $\mathbb{R}^+$는 양의실수의 집합이다)

`(풀이)` 

$x_1 \neq x_2$일때 항상 $\sqrt{x_1}\neq \sqrt{x_2}$이므로 단사이며, 모든 $y\in \mathbb{R}^+$에 대하여 $f(x)=y$를 만족하는 $x=y^2$가 항상 존재하므로 전사이다.